version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    container_name: "flask_container"
    volumes:
      - .:/application
    ports:
      - "8001:8002"
    env_file:
      - .env
    networks:
      - web
    depends_on:
      - db
      - redis_container
    environment:
      - PYTHONUNBUFFERED=1

  db:
    container_name: "postgresql_container"
    image: postgres:14-alpine3.15
    restart: always
    volumes:
      - ./web/postgres:/var/lib/postgresql
    environment:
      - POSTGRES_ROOT_PASSWORD=root
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5444:5432"
    networks:
      - web

  redis_container:
    container_name: redis_container
    image: redis:7.0-rc1-bullseye
    ports:
      - "6363:6379"
    networks:
      - web

networks:
  web:
    driver: bridge